#  /$$   /$$            /$$$$$$  /$$                 /$$ /$$
# | $$$ | $$           /$$__  $$| $$                | $$| $$
# | $$$$| $$ /$$   /$$| $$  \__/| $$$$$$$   /$$$$$$ | $$| $$
# | $$ $$ $$| $$  | $$|  $$$$$$ | $$__  $$ /$$__  $$| $$| $$
# | $$  $$$$| $$  | $$ \____  $$| $$  \ $$| $$$$$$$$| $$| $$
# | $$\  $$$| $$  | $$ /$$  \ $$| $$  | $$| $$_____/| $$| $$
# | $$ \  $$|  $$$$$$/|  $$$$$$/| $$  | $$|  $$$$$$$| $$| $$
# |__/  \__/ \______/  \______/ |__/  |__/ \_______/|__/|__/

startup = [
 "mkdir ~/.cache/starship",
 "starship init nu | save ~/.cache/starship/init.nu",
 "source ~/.cache/starship/init.nu"
]
prompt = "starship_prompt"
skip_welcome_message = true
